name: Terraform Auto-Approve
description: 'Auto-approve terrafrom changes that do not have state changes'
inputs:
  github-token:
    description: 'Github token of the bot used for the auto-approving'
    required: true
  terraform-directory:
    description: 'Root directory for the terraform files'
    required: true
runs:
  using: 'composite'
  steps:
  - run: |
      set -x
      # todo. check that this is a pr and skip (or fail) other workflow events
      pr_number=$(echo "$GIHUB_REF" | cut -d '/' -f3)
      gh pr -R "${GIHUB_REPOSITORY}" view "${pr_number}" --json files --jq '.files.[].path' \
        | grep -qo "^${TERRAFORM_DIR}" && echo "skip=false"|| echo "skip=false" >> $GITHUB_OUTPUT
    shell: bash
    id: check
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      TERRAFORM_DIR: ${{ inputs.terraform-directory }}
  - uses: actions/download-artifact@v3
    if: steps.check.outputs.skip == 'false' # don't fail
    with:
      name: terraform
      path: summary
  - id: summary
    if: steps.check.outputs.skip == 'false' # don't fail
    shell: bash
    run: cat summary/terraform/*.summary | grep 'true' || echo "has_changes=false" >> $GITHUB_OUTPUT
  - uses: hmarr/auto-approve-action@v3
    if: steps.bheck.outputs.skip == 'false' && steps.summary.outputs.has_changes == 'false'
    with:
      github-token: ${{ inputs.github-token }}
