name: Terraform Auto-Approve
description: 'Auto-approve terrafrom changes that do not have state changes'
inputs:
  github-token:
    description: 'Github token of the bot used for the auto-approving'
    required: true
runs:
  using: 'composite'
  steps:
  - uses: actions/download-artifact@v3
    with:
      name: terraform
      path: summary
  - id: summary
    shell: bash
    run: cat summary/terraform/*.summary | grep 'true' || echo "has_changes=false" >> $GITHUB_OUTPUT
  - uses: hmarr/auto-approve-action@v3
    if: steps.summary.outputs.has_changes == 'false'
    with:
      github-token: ${{ inputs.github-token }}
